# Generated by Django 5.1.6 on 2025-07-01 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_room_host"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["updatedAt", "-createdAt"]},
        ),
    ]
